from pathlib import Path

I=Path('app/src/main/assets/index.html'); C=Path('app/src/main/assets/style.css'); J=Path('app/src/main/assets/app.js'); M=Path('app/src/main/java/com/openlocal/office/MainActivity.java')
MARK='File Gestioner spreadsheet interaction layer'

h=I.read_text()
if 'id="spreadsheetTools"' not in h:
    bar='''  <div id="spreadsheetTools" class="spreadsheetTools hidden">
    <b id="selectedCellRef">A1</b><label class="formulaBox"><span>fx</span><input id="formulaInput" autocomplete="off" autocapitalize="off" spellcheck="false" placeholder="Value or formula"></label>
    <div class="sheetQuickActions"><button id="sheetUndo" title="Undo">↶</button><button id="sheetRedo" title="Redo">↷</button><button id="sheetRange" title="Select range">▦</button><button id="sheetCopy" title="Copy">⧉</button><button id="sheetCut" title="Cut">✂</button><button id="sheetPaste" title="Paste">▣</button><button id="sheetClear" title="Clear">⌫</button></div>
  </div>\n'''
    token='  <div id="textFormat" class="formatbar hidden">'
    if token not in h: raise SystemExit('spreadsheet toolbar insertion point missing')
    I.write_text(h.replace(token,bar+token,1))

c=C.read_text()
if MARK not in c:
    C.write_text(c+r'''

/* File Gestioner spreadsheet interaction layer */
.spreadsheetTools{display:grid;grid-template-columns:auto minmax(140px,1fr) auto;gap:7px;align-items:center;padding:7px 10px;background:var(--fg-card,#fff);border-bottom:1px solid var(--fg-border,#ddd);z-index:35}.spreadsheetTools.hidden{display:none!important}
#selectedCellRef{min-width:62px;height:38px;display:grid;place-items:center;padding:0 8px;border:1px solid var(--fg-border,#ddd);border-radius:10px;background:var(--fg-elevated,#fff);font:700 13px ui-monospace,monospace;white-space:nowrap}
.formulaBox{height:38px;display:grid;grid-template-columns:auto minmax(0,1fr);align-items:center;border:1px solid var(--fg-border,#ddd);border-radius:10px;background:var(--fg-elevated,#fff);overflow:hidden}.formulaBox span{padding:0 8px;color:var(--fg-accent,#7187ff);font-weight:800}.formulaBox input{width:100%;min-width:0;height:36px;border:0!important;outline:0!important;box-shadow:none!important;background:transparent!important;color:inherit!important;padding:0 8px 0 0}
.sheetQuickActions{display:flex;gap:4px}.sheetQuickActions button{width:36px;min-width:36px;height:36px;padding:0;display:grid;place-items:center;border:1px solid var(--fg-border,#ddd);border-radius:9px;background:var(--fg-elevated,#fff);color:inherit;font-size:16px}.sheetQuickActions button.active{background:var(--fg-accent,#7187ff)!important;color:#fff}.sheetQuickActions button:disabled{opacity:.35}
#editor table.sheet td{position:relative;cursor:cell;user-select:none;-webkit-user-select:none}#editor table.sheet td.fg-selected{background:color-mix(in srgb,var(--fg-accent,#7187ff) 13%,transparent)!important}#editor table.sheet td.fg-selected::after{content:"";position:absolute;inset:-1px;border:1px solid color-mix(in srgb,var(--fg-accent,#7187ff) 65%,transparent);pointer-events:none}#editor table.sheet td.fg-active::after{content:"";position:absolute;inset:-1px;border:2px solid var(--fg-accent,#7187ff);pointer-events:none;z-index:8}#editor table.sheet td[contenteditable="true"]{cursor:text;user-select:text;-webkit-user-select:text;box-shadow:inset 0 0 0 2px var(--fg-accent,#7187ff);z-index:9}#editor table.sheet th.fg-selected-header{color:var(--fg-accent,#7187ff)!important}
@media(max-width:700px){.spreadsheetTools{grid-template-columns:62px minmax(0,1fr)}.sheetQuickActions{grid-column:1/-1;display:grid;grid-template-columns:repeat(7,1fr)}.sheetQuickActions button{width:100%;min-width:0}.formulaBox input{font-size:16px}}
''')

j=J.read_text()
if MARK not in j:
    J.write_text(j+r'''

/* File Gestioner spreadsheet interaction layer */
(()=>{'use strict';
const $=id=>document.getElementById(id),E=$('editor'),SB=$('sheetBar'),T=$('spreadsheetTools'),F=$('formulaInput'),R=$('selectedCellRef');if(!E||!SB||!T||!F||!R)return;
const S={a:null,z:null,active:null,sheet:-1,pending:null,drag:false,range:false,undo:[],redo:[],editBefore:null,tap:0,tapKey:''},B=()=>window.AndroidBridge||null;
const cells=()=>[...E.querySelectorAll('table.sheet td[data-r][data-c]')],p=td=>td?{row:+td.dataset.r,col:+td.dataset.c}:null,key=q=>q?`${q.row}:${q.col}`:'',at=q=>q?E.querySelector(`td[data-r="${q.row}"][data-c="${q.col}"]`):null;
function alpha(n){let s='';for(n++;n>0;n=Math.floor((n-1)/26))s=String.fromCharCode(65+(n-1)%26)+s;return s}function ref(q){return q?alpha(q.col)+(q.row+1):''}function sheet(){let x=[...($('tabs')?.children||[])].findIndex(x=>x.classList.contains('active'));return Math.max(0,x)}function mode(){return !SB.classList.contains('hidden')&&!!E.querySelector('table.sheet')}
function bounds(){if(!S.a||!S.z)return null;return{r1:Math.min(S.a.row,S.z.row),r2:Math.max(S.a.row,S.z.row),c1:Math.min(S.a.col,S.z.col),c2:Math.max(S.a.col,S.z.col)}}function visible(){let x=cells();if(!x.length)return null,rs=x.map(e=>+e.dataset.r),cs=x.map(e=>+e.dataset.c);return{r1:Math.min(...rs),r2:Math.max(...rs),c1:Math.min(...cs),c2:Math.max(...cs)}}
function ui(){let b=bounds(),q=at(S.active||S.z);R.textContent=!b?'A1':ref({row:b.r1,col:b.c1})+(b.r1===b.r2&&b.c1===b.c2?'':':'+ref({row:b.r2,col:b.c2}));if(document.activeElement!==F)F.value=q?.textContent||'';$('sheetUndo').disabled=!S.undo.length;$('sheetRedo').disabled=!S.redo.length;for(let id of ['sheetCopy','sheetCut','sheetClear'])$(id).disabled=!b;$('sheetRange').classList.toggle('active',S.range)}
function paint(){let b=bounds();E.querySelectorAll('.fg-selected,.fg-active,.fg-selected-header').forEach(x=>x.classList.remove('fg-selected','fg-active','fg-selected-header'));if(b){for(let td of cells()){let q=p(td);if(q.row>=b.r1&&q.row<=b.r2&&q.col>=b.c1&&q.col<=b.c2)td.classList.add('fg-selected')}at(S.active||S.z)?.classList.add('fg-active');let tb=E.querySelector('table.sheet'),vb=visible();if(tb&&vb){let hr=tb.tHead?.rows?.[0];if(hr)for(let i=1;i<hr.cells.length;i++){let td=tb.tBodies[0]?.rows?.[0]?.cells?.[i],q=p(td);if(q&&q.col>=b.c1&&q.col<=b.c2)hr.cells[i].classList.add('fg-selected-header')}for(let tr of [...(tb.tBodies?.[0]?.rows||[])]){let th=tr.cells[0],r=+th.textContent-1;if(r>=b.r1&&r<=b.r2)th.classList.add('fg-selected-header')}}}ui()}
function select(q,extend=false){if(!q)return;if(!extend||!S.a)S.a={...q};S.z={...q};S.active={...q};paint()}function range(a,z){S.a={...a};S.z={...z};S.active={...a};paint()}function prep(td){td.contentEditable='false';td.tabIndex=-1;td.setAttribute('role','gridcell')}
function sync(){let on=mode();T.classList.toggle('hidden',!on);if(!on)return;cells().forEach(prep);let sh=sheet();if(sh!==S.sheet){S.sheet=sh;S.a=S.z=S.active=null}if(S.pending&&at(S.pending)){select(S.pending);at(S.pending)?.scrollIntoView({block:'nearest',inline:'nearest'});S.pending=null}else if(S.active&&at(S.active))paint();else{let td=cells()[0];if(td)select(p(td))}}
function history(ch){ch=ch.filter(x=>x.before!==x.after);if(!ch.length)return;S.undo.push(ch);if(S.undo.length>100)S.undo.shift();S.redo.length=0;ui()}function set(td,v){if(!td)return null;let before=td.textContent||'',after=String(v??'');if(before===after)return null;td.dataset.before=before;td.textContent=after;td.dispatchEvent(new FocusEvent('blur'));prep(td);return{...p(td),before,after}}
function apply(ch,record=true){let done=[];for(let x of ch){let d=set(at(x),x.after);if(d)done.push(d)}if(record)history(done);paint();return done}function undo(){let a=S.undo.pop();if(!a)return;let rev=[];for(let x of a){let td=at(x),cur=td?.textContent||'',d=set(td,x.before);if(d)rev.push({...x,before:x.before,after:cur})}if(rev.length)S.redo.push(rev);ui()}function redo(){let a=S.redo.pop();if(!a)return;let back=[];for(let x of a){let td=at(x),cur=td?.textContent||'',d=set(td,x.after);if(d)back.push({...x,before:cur,after:x.after})}if(back.length)S.undo.push(back);ui()}
function text(){let b=bounds();if(!b)return'';let out=[];for(let r=b.r1;r<=b.r2;r++){let row=[];for(let c=b.c1;c<=b.c2;c++)row.push(at({row:r,col:c})?.textContent||'');out.push(row.join('\t'))}return out.join('\n')}async function write(s){try{if(B()?.setClipboardText){B().setClipboardText(s);return}}catch(_){}try{await navigator.clipboard.writeText(s);return}catch(_){}const t=document.createElement('textarea');t.value=s;t.setAttribute('readonly','');t.style.cssText='position:fixed;left:-9999px;top:0;opacity:0';document.body.appendChild(t);t.select();try{document.execCommand('copy')}finally{t.remove()}}async function read(){try{if(B()?.getClipboardText)return B().getClipboardText()||''}catch(_){}try{return await navigator.clipboard.readText()}catch(_){return''}}
async function copy(cut=false){await write(text());if(cut)clear()}function clear(){let b=bounds(),ch=[];if(!b)return;for(let r=b.r1;r<=b.r2;r++)for(let c=b.c1;c<=b.c2;c++)if(at({row:r,col:c}))ch.push({row:r,col:c,after:''});apply(ch)}function paste(s){if(!S.active||!s)return;let rows=String(s).replace(/\r\n?/g,'\n').replace(/\n$/,'').split('\n').map(x=>x.split('\t')),vb=visible(),ch=[];rows.forEach((row,dr)=>row.forEach((v,dc)=>{let q={row:S.active.row+dr,col:S.active.col+dc};if(vb&&q.row<=vb.r2&&q.col<=vb.c2)ch.push({...q,after:v})}));let d=apply(ch);if(d.length)range(S.active,{row:d[d.length-1].row,col:d[d.length-1].col})}
function edit(td,repl=null){if(!td)return;select(p(td));S.editBefore=td.textContent||'';td.contentEditable='true';td.dataset.before=td.textContent||'';td.focus({preventScroll:true});if(repl!==null){td.textContent=repl;let r=document.createRange();r.selectNodeContents(td);r.collapse(false);let s=getSelection();s.removeAllRanges();s.addRange(r)}}function move(dr,dc,extend=false){let q=S.active||p(cells()[0]);if(!q)return;let n={row:Math.max(0,q.row+dr),col:Math.max(0,q.col+dc)};if(at(n)){select(n,extend);at(n).focus()}else{S.pending=n;$('goCell').value=ref(n);$('goCellBtn').click()}}
E.addEventListener('click',e=>{if(!mode())return;let th=e.target.closest('th'),vb=visible();if(th&&vb){if(th.closest('thead')){if(th.classList.contains('corner'))range({row:vb.r1,col:vb.c1},{row:vb.r2,col:vb.c2});else{let i=th.cellIndex,td=E.querySelector(`tbody tr td:nth-child(${i+1})`),q=p(td);if(q)range({row:vb.r1,col:q.col},{row:vb.r2,col:q.col})}}else if(th.classList.contains('rowh')){let r=+th.textContent-1;range({row:r,col:vb.c1},{row:r,col:vb.c2})}return}let td=e.target.closest('td[data-r][data-c]');if(!td||td.contentEditable==='true')return;let now=Date.now(),k=key(p(td));if(S.tapKey===k&&now-S.tap<420){edit(td);S.tap=0;S.tapKey=''}else{S.tap=now;S.tapKey=k;select(p(td),e.shiftKey)}} ,true);
E.addEventListener('dblclick',e=>{let td=e.target.closest('td[data-r][data-c]');if(td){e.preventDefault();edit(td)}} ,true);E.addEventListener('focusout',e=>{let td=e.target.closest?.('td[data-r][data-c]');if(td&&td.contentEditable==='true')queueMicrotask(()=>{let q=p(td),before=S.editBefore??td.dataset.before??'',after=td.textContent||'';S.editBefore=null;if(before!==after){td.dataset.before=before;td.dispatchEvent(new FocusEvent('blur'));history([{...q,before,after}])}prep(td);select(q)})});
E.addEventListener('pointerdown',e=>{let td=e.target.closest('td[data-r][data-c]');if(!td||td.contentEditable==='true'||(e.pointerType==='touch'&&!S.range))return;S.drag=true;select(p(td),e.shiftKey);if(e.pointerType==='touch')e.preventDefault()} ,{capture:true,passive:false});E.addEventListener('pointermove',e=>{if(!S.drag)return;let td=document.elementFromPoint(e.clientX,e.clientY)?.closest?.('td[data-r][data-c]');if(td){S.z=p(td);S.active=p(td);paint();e.preventDefault()}} ,{capture:true,passive:false});['pointerup','pointercancel'].forEach(x=>E.addEventListener(x,()=>S.drag=false,true));
document.addEventListener('keydown',e=>{if(!mode())return;let a=document.activeElement,editing=a?.matches?.('td[contenteditable="true"],#formulaInput,input,textarea,select'),m=e.ctrlKey||e.metaKey,k=(e.key||'').toLowerCase();if(editing&&a?.id!=='formulaInput')return;if(m&&k==='z'){e.preventDefault();e.shiftKey?redo():undo();return}if(m&&k==='y'){e.preventDefault();redo();return}if(m&&k==='c'){e.preventDefault();copy();return}if(m&&k==='x'){e.preventDefault();copy(true);return}if(a?.id==='formulaInput')return;if(e.key==='ArrowUp'){e.preventDefault();move(-1,0,e.shiftKey)}else if(e.key==='ArrowDown'){e.preventDefault();move(1,0,e.shiftKey)}else if(e.key==='ArrowLeft'){e.preventDefault();move(0,-1,e.shiftKey)}else if(e.key==='ArrowRight'){e.preventDefault();move(0,1,e.shiftKey)}else if(e.key==='Enter'){e.preventDefault();move(e.shiftKey?-1:1,0)}else if(e.key==='Tab'){e.preventDefault();move(0,e.shiftKey?-1:1)}else if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();clear()}else if(e.key==='F2'){e.preventDefault();edit(at(S.active))}else if(!m&&!e.altKey&&e.key.length===1){e.preventDefault();edit(at(S.active),e.key)}} ,true);
document.addEventListener('paste',e=>{if(!mode()||document.activeElement?.matches?.('td[contenteditable="true"],#formulaInput,input,textarea'))return;let s=e.clipboardData?.getData('text/plain');if(s!=null){e.preventDefault();paste(s)}} ,true);
F.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();let td=at(S.active),before=td?.textContent||'',d=set(td,F.value);if(d)history([d]);paint()}else if(e.key==='Escape'){F.value=at(S.active)?.textContent||'';at(S.active)?.focus()}});F.addEventListener('change',()=>{let d=set(at(S.active),F.value);if(d)history([d]);paint()});
$('sheetUndo').onclick=undo;$('sheetRedo').onclick=redo;$('sheetRange').onclick=()=>{S.range=!S.range;ui()};$('sheetCopy').onclick=()=>copy();$('sheetCut').onclick=()=>copy(true);$('sheetPaste').onclick=async()=>paste(await read());$('sheetClear').onclick=clear;
new MutationObserver(sync).observe(E,{childList:true,subtree:true});new MutationObserver(sync).observe(SB,{attributes:true,attributeFilter:['class']});sync();
})();
''')

m=M.read_text()
if False and 'getClipboardText()' not in m:
    n='''        @JavascriptInterface public void setSdocxText(String value){
            try { if(sdocx!=null)sdocx.setText(value); }
            catch(Exception e){ runOnUiThread(() -> js("window.showError("+q(message(e))+")")); }
        }'''
    if n not in m: raise SystemExit('clipboard bridge insertion point missing')
    a=n+'''\n        @JavascriptInterface public String getClipboardText(){try{android.content.ClipboardManager c=(android.content.ClipboardManager)MainActivity.this.getSystemService(android.content.Context.CLIPBOARD_SERVICE);if(c==null||!c.hasPrimaryClip())return "";android.content.ClipData d=c.getPrimaryClip();if(d==null||d.getItemCount()==0)return "";CharSequence t=d.getItemAt(0).coerceToText(MainActivity.this);return t==null?"":t.toString();}catch(Exception e){return "";}}\n        @JavascriptInterface public void setClipboardText(String v){try{android.content.ClipboardManager c=(android.content.ClipboardManager)MainActivity.this.getSystemService(android.content.Context.CLIPBOARD_SERVICE);if(c!=null)c.setPrimaryClip(android.content.ClipData.newPlainText("Spreadsheet cells",v==null?"":v));}catch(Exception ignored){}}'''
    M.write_text(m.replace(n,a,1))
